FROM public.ecr.aws/ubuntu/ubuntu:jammy

ENV container="docker"

RUN set -ex ; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt update ; \
    apt install -y systemd \
      systemd-sysv \
      iproute2 \
      python3 \
      sudo \
      hostname \
      procps \
      ca-certificates \
      gnupg \
      netcat-openbsd \
      socat \ 
      curl ; \
    apt clean all ; \
    rm -rf \
      /var/lib/apt/lists/* \
      /var/cache/debconf/* \
      /tmp/* \
      /var/tmp/* \
      /var/log/* ;

RUN truncate -s0 /etc/machine-id

STOPSIGNAL SIGRTMIN+3

CMD [ "/sbin/init" ]
