---
name: Build Ubuntu Molecule image
on:
  push:
    branches:
      - main
    paths:
      - ubuntu/**
      - .github/workflows/ubuntu.yml
#  schedule:
#    - cron: ''
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ['jammy']
    steps:
      - name: Generate build id (based on timestamp)
        run: |
          echo BUILD_ID=$(date +'%Y%m%d%H%M') >> $GITHUB_ENV

      - name: Check-out repository
        uses: actions/checkout@v4
          
      - name: Set up QEMU (for multi-arch build)
        uses: docker/setup-qemu-action@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Login to Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_HUB_USERNAME }}
          password: ${{ secrets.REGISTRY_HUB_PASSWORD }}
          
      - name: Build and push image to Docker Hub registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./ubuntu
          file: ./ubuntu/Dockerfile.${{ matrix.release }}
          push: true
          build-args: |
            RELEASE=${{ matrix.release }}
          tags: |
            ${{ secrets.REGISTRY_HUB_USERNAME }}/molecule-ubuntu:${{ matrix.release }}
            ${{ secrets.REGISTRY_HUB_USERNAME }}/molecule-ubuntu:${{ matrix.release }}-${{ env.BUILD_ID }}